### ISSUE TITLE
Bug: The stop play action button doesn't work

### ISSUE THREAD

**Issue by haxshith** [Suraj-Upadhyay/Algorithm-Visualiser#2]
can you please brief me how to do this exactly.

**Comment by Suraj-Upadhyay** [comment]
Please study the source code for the Visualiser component.

There can be two possibilities:

1. The stop play action button may not be setting the isPlaying variable to false.

Or

2. The useEffect hook isn't able to properly stop the setInterval calling algorithm object's stepForward method.

We can discuss this further.

**Comment by Suraj-Upadhyay** [comment]
Hi @haxshith, This issue is a part of another Isse #3  that I have created and should be solved under that issue instead. You can continue working on this issue and raise a PR when you are done. Closing this one.
