### ISSUE TITLE
Bug: Play Action controls are not working properly

### ISSUE THREAD

**Issue by Suraj-Upadhyay** [Suraj-Upadhyay/Algorithm-Visualiser#3]
Play Action controls that **pause**, **resume**, **step forward**
and **step backward** are not working as intended.

1. The **pause** button doesn't stop the algorithm from playing. (As described in #2 )
2. The **resume** button doesn't resume 'play action' of a paused algorithm.
3. **Step Forwards/Backwards** don't even have their functionalities yet.

Along with fixing the above behaviours, also make sure that:
1. The **Pause** button, actually starts as a **start** button and then transitions
    over to a **pause** button after getting clicked.
2. And the same **pause** button referenced in point 1, transitions into **resume** button
    and back to **pause** button when clicked.
3. The second button should be a **Terminate** button, which would stop the algorithm altogether.
4. And the next two buttons would be **Step Forward** and **Step Backwards**.

Also, in consideration, disable the action buttons that are not needed.
1. Disable all the buttons before starting.
2. Disable Step forwards/Backwards when the algorithm is running
    and enable them only when the algorithm is paused.
3. After pressing **terminate**, all the action buttons should be disabled again,
    and the data view should get cleared.
4. ***EDIT***: Disable all the Play Action Controls, before the algorithms has started
     and after it has been terminated.

The workings of all the above controls should be intuitive.

**Comment by haxshith** [comment]
yeah I started working on them as am combining both play and pause buttons as same am facing some issues on this.
<img width="1440" alt="Screenshot 2024-01-31 at 2 36 04 PM" src="https://github.com/Suraj-Upadhyay/Algorithm-Visualiser/assets/123642030/bbaff203-2cec-4e7d-b753-71a16681a3d9">

**Comment by Suraj-Upadhyay** [comment]
Hi @haxshith can you send a "work in progress" PR with this code, I am not able to see what all code changes you have made.

**Comment by Suraj-Upadhyay** [comment]
Closed by #23

**Comment by Suraj-Upadhyay** [comment]
Fixed By #23
